@startuml
start

:Check parameters valid;

if (Parameters are null or out of range?) then (Yes)
  :Return MANIKIN_STATUS_ERR_NULL_PARAM;
else (No)
  :Check for sensor presence;
  if (Sensor present?) then (Yes)
    :Initialize sensor with default settings\n(continuous mode);
    :Return MANIKIN_STATUS_OK;
  else (No)
    :Return \nMANIKIN_STATUS_ERR_SENSOR_INIT_FAIL;
  endif
endif

stop
@enduml
