#ifndef SDP810_REGS_H
#define SDP810_REGS_H
#ifdef __cplusplus
extern "C"
{
#endif

#define SDP810_REG_CONT_MASS_FLOW     (0x36 << 8 | 0x03)
#define SDP810_READ_BUFFER_SIZE       9
#define SDP810_READ_DIFF_PRESSURE_MSB 0
#define SDP810_READ_DIFF_PRESSURE_LSB 1
#define SDP810_READ_DIFF_PRESSURE_CRC 2
#define SDP810_READ_TEMPERATURE_MSB   3
#define SDP810_READ_TEMPERATURE_LSB   4
#define SDP810_READ_TEMPERATURE_CRC   5
#define SDP810_READ_SCALE_FACTOR_MSB  6
#define SDP810_READ_SCALE_FACTOR_LSB  7
#define SDP810_READ_SCALE_FACTOR_CRC  8

#ifdef __cplusplus
}
#endif
#endif // SDP810_REGS_H
