@startuml
title Flash Module - Public API Overview

' --- Flash Module API Class ---
class "<memory_module>" {
  +manikin_status_t <memory_module>_init(manikin_spi_memory_ctx_t *mem_ctx)
  +manikin_status_t <memory_module>_status(manikin_spi_memory_ctx_t *mem_ctx)
  +manikin_memory_result_t <memory_module>_write(mem_ctx, data, addr, len)
  +manikin_memory_result_t <memory_module>_read(mem_ctx, data, addr, len)
  +manikin_memory_result_t <memory_module>_erase_sector(mem_ctx, sector_number)
  +manikin_status_t <memory_module>_deinit(manikin_spi_memory_ctx_t *mem_ctx)
}

'<memory_module> depends on context and return types

@enduml

