@startuml
actor "Application" as App
participant "Sensor Module" as Sensor

App -> Sensor : <sensor>_init_sensor(sensor_ctx)
activate Sensor
Sensor --> App : MANIKIN_STATUS_OK / error
deactivate Sensor

App -> Sensor : <sensor>_read_sensor(sensor_ctx, read_buf)
activate Sensor
Sensor --> App : MANIKIN_STATUS_OK / error
deactivate Sensor

... repeat read as needed ...

App -> Sensor : <sensor>_deinit_sensor(sensor_ctx)
activate Sensor
Sensor --> App : MANIKIN_STATUS_OK
deactivate Sensor
@enduml
