name: Test run (x86_64)
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install prerequired packages
        # To compile and run the code we require cmake, gcc and ninja
        run:  sudo apt-get update && sudo apt-get install build-essential cmake ninja-build

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -G Ninja -DMANIKIN_SOFTWARE_BUILD_TESTS=ON

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build
      - name: Test
        run: cd ${{github.workspace}}/build && ctest --rerun-failed --output-on-failure --output-junit results.xml
      
      - name: Report tests
        uses: dorny/test-reporter@v1
        with:
          name: JUnit Tests
          path: ${{github.workspace}}/build/results.xml
          reporter: java-junit